# This CI configuration tests the cosmwasm-template repository itself,
# not the resulting project. We want to ensure that
# 1. the template to project generation works
# 2. the template files are up to date
#
# We chose Appveyor for this task as it allows us to use an arbitrary config
# location. Furthermore it allows us to ship a Circle CI and Travis config
# generated for the resulting project.

# I'm having a hard time with the caching below and variable interpolation
# Free free to add later and update the install script, but make sure caching works

#environment:
#  matrix:
#    - TARGET: x86_64-pc-windows-msvc
#      CHANNEL: stable
##    - TARGET: x86_64-pc-windows-msvc
##      CHANNEL: nightly

cache:
  - 'C:\Users\appveyor\.rustup'
  - 'C:\Users\appveyor\.cargo\bin'
  - 'C:\Users\appveyor\.cargo\registry'
  - 'C:\projects\test-generation-in-ci\target\debug\.fingerprint -> Cargo.lock, Cargo.toml'
  - 'C:\projects\test-generation-in-ci\target\debug\build -> Cargo.lock, Cargo.toml'
  - 'C:\projects\test-generation-in-ci\target\debug\deps -> Cargo.lock, Cargo.toml'
  - 'C:\projects\test-generation-in-ci\target\wasm32-unknown-unknown\release\.fingerprint -> Cargo.lock, Cargo.toml'
  - 'C:\projects\test-generation-in-ci\target\wasm32-unknown-unknown\release\build -> Cargo.lock, Cargo.toml'
  - 'C:\projects\test-generation-in-ci\target\wasm32-unknown-unknown\release\deps -> Cargo.lock, Cargo.toml'

install:
  - ps: if (-not (Test-Path 'C:\Users\appveyor\.cargo\bin\rustc.exe')) { appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe ; .\rustup-init.exe --profile minimal --default-host x86_64-pc-windows-msvc --default-toolchain stable -y; echo okay }
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc --version
  - cargo --version
  - rustup target add wasm32-unknown-unknown
  - ps: if (-not (Test-Path 'C:\Users\appveyor\.cargo\bin\cargo-generate.exe')) { cargo install cargo-generate --features vendored-openssl; echo okay }

build_script:
  - cd ..
  - ps: if (Test-Path 'test-generation-in-ci/target') { Move-Item test-generation-in-ci/target target-cache; Remove-Item -path test-generation-in-ci -recurse }
  - cargo generate --git cosmwasm-template --name test-generation-in-ci
  - ps: if (Test-Path 'target-cache') { Move-Item target-cache test-generation-in-ci/target }
  - cd test-generation-in-ci
  - dir
  - cargo unit-test
  - cargo wasm
  - cargo test
  - cargo schema

# whitelist long living branches
branches:
  only:
    - master
